---

- name: install monitoring stack
  hosts: monitoring
  vars_files:
    - defaults/main.yml
  become: true
  roles:
    - prometheus
    - elasticsearch
    - kibana

- name: install node-exporter
  hosts: monitoring_agents
  vars_files:
    - defaults/main.yml
  become: true
  roles:
    - node-exporter
    - fluentbit
