---
- name: install monitoring stack
  hosts: monitoring
  become: true
  roles:
    - prometheus
    - elasticsearch
    - kibana

- name: install node-exporter
  hosts: monitoring_agents
  become: true
  roles:
    - node-exporter
    - fluentbit
