---
# tasks file for kibana
- name: Update repositories cache and install "kibana" package
  ansible.builtin.apt:
    name: kibana
    update_cache: yes
  notify: reload_daemon_and_restart_kibana
- meta: flush_handlers
- name: service always started
  ansible.builtin.systemd:
    name: kibana
    state: started
    enabled: true
 